twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:  ['bootstrap_5_layout.html.twig']
    globals: 
        application_tracking: 'UA-xxxxx-x'
        application_name: 'Hello word'

when@test:
    twig:
        strict_variables: true
